name: Docker Image CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

     # - name: Build and push latest
      #  id: docker_build
       # uses: docker/build-push-action@v2
        #with:
         # context: latest
          #file: latest/Dockerfile
          #push: true
          #tags: shrutir11/jupyterlab-datascience:latest

      - name: Build and push 2.2.9
        id: docker_build_two_two_nine
        uses: docker/build-push-action@v2
        with:
          context: 2.2.9
          file: 2.2.9/Dockerfile
          push: true
          tags: shrutir11/jupyterlab-datascience:2.2.9
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
